services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRER_DB=shop
      - POSTGRER_USER=postgres
      - POSTGRER_PASSWORD=sakineh13755
    networks:
      - main
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data

  app:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: app
    volumes:
      - .:/djangoshop/
    depends_on:
      - postgres
    expose:
      - "8000"
    networks:
      - main
    restart: always

networks:
  main:

volumes:
  postgres_data: